package code.database;

import android.app.Activity;

public final class AppSettings extends OSettings {
    public static final String PREFS_MAIN_FILE             = "PREFS_KMCAPP_FILE";
    public static final String userId                            = "userId";
    public static final String loungeId                            = "loungeId";
    public static final String loginDistrict                            = "loginDistrict";
    public static final String nurseId                            = "nurseId";
    public static final String newNurseId                            = "newNurseId";
    public static final String newNurseSelfie                            = "newNurseSelfie";
    public static final String fcmId = "fcmId";
    public static final String syncTime                          = "syncTime";
    public static final String geoSyncTime                          = "geoSyncTime";
    public static final String posterSyncTime                          = "posterSyncTime";

    public static final String kmcPosition                          = "kmcPosition";
    public static final String staffSyncTime                          = "staffSyncTime";
    public static final String doctorRoundSyncTime        = "doctorRoundSyncTime";
    public static final String doctorName                           = "doctorName";
    public static final String loginId                                      = "loginId";
    public static final String loginTime                                 = "loginTime";
    public static final String facId                                        = "facId";
    public static final String facName                                = "facName";
    public static final String dischargeCondtion             = "dischargeCondtion";
    public static final String accessToken                   = "accessToken";
    public static final String keyLanguageCode       = "keyLanguageCode";
    public static final String lastAssessmentDate       = "lastAssessmentDate";
    public static final String motherId       = "motherId";
    public static final String babyId       = "babyId";
    public static final String babyPic       = "babyPic";
    public static final String babyName       = "babyName";
    public static final String babyAssDate       = "babyAssDate";
    public static final String babyStep       = "babyStep";
    public static final String babyBW               = "babyBW";
    public static final String babyMCTS               = "babyMCTS";
    public static final String motherAdmissionId       = "motherAdmissionId";
    public static final String babyAdmissionId       = "babyAdmissionId";
    public static final String position       = "position";
    public static final String respiratoryRate = "respiratoryRate";
    public static final String takeWeight = "takeWeight";
    public static final String motherPhoto       = "motherPhoto";
    public static final String motherName       = "motherName";
    public static final String motherMCTS       = "motherMCTS";
    public static final String motherAssDate       = "motherAssDate";
    public static final String motherStep       = "motherStep";
    public static final String babyList       = "babyList";
    public static final String ashaName       = "ashaName";
    public static final String ashaNumber       = "ashaNumber";
    public static final String uuid       = "uuid";
    public static final String from       = "from";
    public static final String checkHRN       = "checkHRN";
    public static final String villageCount       = "villageCount";
    public static final String villageCountNew       = "villageCountNew";
    public static final String notificationId       = "notificationId";
    public static final int day       = 0;
    public static final String babyFileId           = "babyFileId";
    public static final String gender                   = "gender";
    public static final String delivery             = "delivery";
    public static final String babyWeight       = "babyWeight";
    public static final String babyDelDnT       = "babyDelDnT";
    public static final String babyDel       = "babyDel";
    public static final String babyGest       = "babyGest";
    public static final String motherLMPDate       = "motherLMPDate";
    public static final String hours = "hours";
    public static final String hrn = "hrn";
    public static final String videoFrom = "videoFrom";
    public static final String lastActivity = "lastActivity";
    public static final String points = "points";
    public static final String token = "token";
    public static final String bMonId = "bMonId";
    public static final String bAdmId = "bAdmId";
    public static final String mMonId = "mMonId";
    public static final String mAdmId = "mAdmId";
    public static final String admissionDate = "admissionDate";
    public static final String type = "type";
    public static final String timestamp = "timestamp";
    public static final String babyFrom = "babyFrom";
    public static final String userType = "userType";
    public static final String checkIMEI = "checkIMEI";
    public static final String latitude = "latitude";
    public static final String longitude = "longitude";
    public static final String loungeName = "loungeName";
    public static final String name = "name";
    public static final String staffType = "staffType";
    public static final String jobType = "jobType";
    public static final String image = "image";
    public static final String mobileNo = "mobileNo";
    public static final String emergencyNo = "emergencyNo";
    public static final String address = "address";
    public static final String addDate = "addDate";
    public static final String staffSubTypeId = "staffSubTypeId";
    public static final String staffTypeId = "staffTypeId";
    public static final String staffSubType = "staffSubType";
    public static final String lmpDate = "lmpDate";
    public static final String loungeType = "loungeType"; //1 SNCU - 2 Lounge
    public static final String invesName = "invesName";
    public static final String moveStatus = "moveStatus";
    public static final String isSibling = "isSibling";
    public static final String babyDirectoryUrl = "babyDirectoryUrl";
    public static final String motherDirectoryUrl = "motherDirectoryUrl";
    public static final String sehmatiPatraUrl = "sehmatiPatraUrl";
    public static final String signDirectoryUrl = "signDirectoryUrl";
    public static final String babyWeightDirectoryUrl = "babyWeightDirectoryUrl";
    public static final String investigationDirectoryUrl = "investigationDirectoryUrl";
    public static final String coachId = "coachId";
    public static final String incorrectLoginAttempt = "incorrectLoginAttempt";
    public static final String incorrectLoginTime = "incorrectLoginTime";

    public static final String WhatisKmcViewer              = "whatisKmcViewer";
    public static final String kmcPositionViewer              = "kmcPositionViewer";
    public static final String kmcNutitionViewer              = "kmcNutitionViewer";
    public static final String kmcHygieneViewer              = "kmcHygieneViewer";
    public static final String kmcMonitoringViewer             = "kmcMonitoringViewer";
    public static final String kmcRespectViewer              = "kmcRespectViewer";

    public static final String WhatisKmcposition                = "WhatisKmcposition";
    public static final String kmcPositionposition                = "kmcPositionposition";
    public static final String kmcNutitionposition                = "kmcNutitionposition";
    public static final String kmcHygieneposition                = "kmcHygieneposition";
    public static final String kmcMonitoringposition                = "kmcMonitoringposition";
    public static final String kmcRespectposition                = "kmcRespectposition";
    public static final String  positionValue               = "positionValue";

    public AppSettings(Activity mActivity) {
        super(mActivity);
    }
}
